# AUTOGENERATED! DO NOT EDIT! File to edit: fasthlight.ipynb.

# %% auto 0
__all__ = ['db', 'highlights_db', 'app', 'rt', 'HighlightData', 'rgb_to_hex', 'extract_highlights', 'Highlight',
           'save_highlights', 'highlight_card', 'index', 'view_pdf', 'upload']

# %% fasthlight.ipynb 1
from fasthtml.common import *
from fasthtml.jupyter import JupyUvi, HTMX
from monsterui.all import *

# %% fasthlight.ipynb 2
import fitz  # PyMuPDF
from dataclasses import dataclass
from datetime import datetime
from collections import Counter

# %% fasthlight.ipynb 3
@dataclass
class HighlightData:
    text: str
    page: int
    color: str  # We'll store as string for simplicity
    created: datetime  # ISO format datetime string

# %% fasthlight.ipynb 8
def rgb_to_hex(rgb_tuple):
    """Convert RGB tuple (0-1 range) to hex color string"""
    r, g, b = [int(c * 255) for c in rgb_tuple]
    return f"#{r:02x}{g:02x}{b:02x}"

# %% fasthlight.ipynb 9
def extract_highlights(path):
    highlights = L()
    doc = fitz.open(path)

    try:
        for page_num in range(len(doc)):
            page = doc[page_num]
            annots = page.annots()
            if not annots: continue
            
            for annot in annots:
                # annotations (type 8), underline (9), strikeout (10), squiggly (11)
                if annot.type[0] not in [8, 9, 10, 11]: continue
    
                quads = annot.vertices
                highlighted_text = ""
                for i in range(0, len(quads), 4):
                    rect = fitz.Quad(quads[i:i+4]).rect
                    highlighted_text += page.get_text("text", clip=rect).strip()
                    
                hex_color = rgb_to_hex(annot.colors.get("stroke", (1.0, 1.0, 0.0)))
                
                highlights.append(HighlightData(
                    text=highlighted_text,
                    page=page_num + 1,
                    color=hex_color,
                    created=datetime.now()
                ))
            
    finally:
        doc.close()
    
    return highlights

# %% fasthlight.ipynb 11
# Create/open database
db = database('highlights.db')

# Define your table structure - fastlite works great with dataclasses
@dataclass
class Highlight:
    id: int
    text: str
    page: int
    color: str  # We'll store as string for simplicity
    pdf_file: str  # Track which PDF it came from
    created: str  # ISO format datetime string

# Create the table (transform=True allows schema updates)
highlights_db = db.create(Highlight, pk='id', transform=True)

# %% fasthlight.ipynb 13
def save_highlights(pdf_path, highlights):
    "Save extracted highlights to database"
    pdf_name = Path(pdf_path).name
    for h in highlights:
        highlights_db.insert(
            text=h.text,
            page=h.page,
            color=h.color,  # Convert tuple to string
            pdf_file=pdf_name,
            created=h.created.isoformat()
        )

# %% fasthlight.ipynb 17
def highlight_card(h):
    # Parse color and convert to CSS
    color_style = f"background-color: {h.color};"
    
    return Card(
        # Color indicator strip - using inline style instead of Tailwind classes
        Div(cls="absolute left-0 top-0 bottom-0 w-1", style=color_style),
        # Main content with padding to avoid color strip
        Div(
            P(h.text, cls=TextPresets.md_weight_sm),
            cls="pl-4"
        ),
        footer=DivFullySpaced(
            DivHStacked(
                UkIcon('file-text', height=16),
                P(h.pdf_file, cls=TextPresets.muted_sm)
            ),
            DivHStacked(
                UkIcon('book-open', height=16),
                P(f"Page {h.page}", cls=TextPresets.muted_sm)
            )
        ),
        cls=CardT.hover,
        style="position: relative;"
    )

# %% fasthlight.ipynb 19
# Initialize FastHTML app with MonsterUI theme
app, rt = fast_app(hdrs=Theme.blue.headers())

# %% fasthlight.ipynb 20
@app.route('/')
def index():
    pdf_counts = Counter(h.pdf_file for h in highlights_db())

    pdf_cards = [
        Card(
            H3(pdf_name),
            P(f'{count} highlights', cls=TextPresets.muted_sm),
            footer = Button("View Highlights",
                                     hx_get=f"/pdf/{pdf_name}",
                                     hx_target="#main-content",
                                     cls=ButtonT.primary),
            cls=CardT.hover
        )
        for pdf_name, count in pdf_counts.items()
    ]  

    # Upload form
    upload_form = Card(
        H3("Upload New PDF"),
        Form(
            Input(type="file", name="pdf_file", accept=".pdf"),
            Button("Upload & Analyze", type="submit", cls=ButtonT.primary),
            hx_post="/upload",
            hx_target="#main-content",
            enctype="multipart/form-data"
        )
    )

    return Titled(
        "PDF Highlights Manager",
        Div(
            upload_form,
            Divider(),
            H2("Your PDFs"),
            Grid(*pdf_cards, cols=3),
            id="main-content",
            cls="space-y-6"
        )
    )

# %% fasthlight.ipynb 21
@app.route('/pdf/{pdf_name}')
def view_pdf(pdf_name:str):
    highlights = highlights_db(where="pdf_file=?", where_args=(pdf_name,), order_by='page')
    cards = [highlight_card(h) for h in highlights]

    return Div(
        DivFullySpaced(
            H2(pdf_name),
            Button("← Back", hx_get="/", hx_target="#main-content", cls=ButtonT.ghost)
        ),
        Div(*cards, cls='space-y-4')
    )

# %% fasthlight.ipynb 22
@app.route('/upload', methods=['POST'])
async def upload(pdf_file: UploadFile):
    content = await pdf_file.read()

    new_highlights = extract_highlights(content)
    save_highlights(pdf_file.filename, new_highlights)
    
    return Div(
        Alert(
            f"Successfully extracted {len(new_highlights)} highlights from {pdf_file.filename}!",
            cls=AlertT.success
        ),
        # Trigger a refresh to show the new PDF card
        Div(hx_get="/", hx_trigger="load delay:2s", hx_target="#main-content")
    )
