# AUTOGENERATED! DO NOT EDIT! File to edit: fasthlight.ipynb.

# %% auto 0
__all__ = ['data_dir', 'db', 'highlights_db', 'users_db', 'app', 'rt', 'HighlightData', 'rgb_to_hex', 'extract_highlights',
           'Highlight', 'pdf_basename', 'save_highlights', 'highlight_card', 'User', 'hash_pwd', 'verify_pwd',
           'get_current_user', 'index', 'view_source', 'upload', 'save_web_highlight', 'login_page', 'do_login',
           'signup_page', 'do_signup', 'logout', 'bookmarklet_page']

# %% fasthlight.ipynb 1
from fasthtml.common import *
from fasthtml.jupyter import JupyUvi, HTMX
from monsterui.all import *
import os
from dotenv import load_dotenv

# %% fasthlight.ipynb 2
import fitz  # PyMuPDF
from dataclasses import dataclass
from datetime import datetime
from collections import Counter
from typing import Union
import hashlib

# %% fasthlight.ipynb 6
@dataclass
class HighlightData:
    text: str
    page: int
    color: str  # We'll store as string for simplicity
    created: datetime  # ISO format datetime string

# %% fasthlight.ipynb 11
def rgb_to_hex(rgb_tuple):
    """Convert RGB tuple (0-1 range) to hex color string"""
    r, g, b = [int(c * 255) for c in rgb_tuple]
    return f"#{r:02x}{g:02x}{b:02x}"

# %% fasthlight.ipynb 13
def extract_highlights(pdf: Union[str, Path, bytes]):
    """Extract highlights from PDF file path or bytes content"""
    highlights = L()
    
    doc = fitz.open(pdf) if isinstance(pdf, (str, Path)) else fitz.open(stream=pdf, filetype="pdf")

    try:
        for page_num in range(len(doc)):
            page = doc[page_num]
            annots = page.annots()
            if not annots: continue
            
            for annot in annots:
                # annotations (type 8), underline (9), strikeout (10), squiggly (11)
                if annot.type[0] not in [8, 9, 10, 11]: continue
    
                quads = annot.vertices
                highlighted_text = ""
                for i in range(0, len(quads), 4):
                    rect = fitz.Quad(quads[i:i+4]).rect
                    highlighted_text += page.get_text("text", clip=rect).strip()
                    
                hex_color = rgb_to_hex(annot.colors.get("stroke", (1.0, 1.0, 0.0)))
                
                highlights.append(HighlightData(
                    text=highlighted_text,
                    page=page_num + 1,
                    color=hex_color,
                    created=datetime.now()
                ))
            
    finally:
        doc.close()
    
    return highlights

# %% fasthlight.ipynb 18
# Create/open database
data_dir = Path('/data') if Path('/data').exists() else Path('.')
data_dir.mkdir(exist_ok=True)
db = database(data_dir/'highlights.db')

# Define your table structure - fastlite works great with dataclasses
@dataclass
class Highlight:
    id: int
    user_id: int
    text: str
    color: str  # We'll store as string for simplicity
    source: str # PDF filename or URL
    source_type: str # 'pdf' or 'web'
    title: str  # Page title for web highlights
    created: str  # ISO format datetime string
    page: int = None

# Create the table (transform=True allows schema updates)
highlights_db = db.create(Highlight, pk='id', transform=True)

# %% fasthlight.ipynb 20
def pdf_basename(filename):
    """Get filename without extension"""
    return Path(filename).stem

# %% fasthlight.ipynb 22
def save_highlights(pdf_path, highlights, user_id):
    "Save extracted highlights to database"
    pdf_name = pdf_basename(pdf_path)
    for h in highlights:
        highlights_db.insert(
            user_id=user_id,
            text=h.text,
            page=h.page,
            color=h.color,  # Convert tuple to string
            source=pdf_name,
            source_type='pdf',
            title=f"{pdf_name}.pdf",
            created=h.created.isoformat()
        )

# %% fasthlight.ipynb 28
def highlight_card(h):
    "Render a highlight card for both PDF and web highlights"
    color_style = f"background-color: {h.color};"

    # Choose icon based on source type
    icon = 'file-text' if h.source_type == 'pdf' else 'globe'

    # For PDFs show page, for web show domain
    if h.source_type == 'pdf':
        location_info = DivHStacked(
            UkIcon('book-open', height=16),
            P(f"Page {h.page}", cls=TextPresets.muted_sm)
        )
    else:
        # Extract domain from URL for cleaner display
        from urllib.parse import urlparse
        domain = urlparse(h.source).netloc or h.source
        location_info = DivHStacked(
            UkIcon('link', height=16),
            P(domain, cls=TextPresets.muted_sm)
        )
    
    return Card(
        # Color indicator strip - using inline style instead of Tailwind classes
        Div(cls="absolute left-0 top-0 bottom-0 w-1", style=color_style),
        # Main content with padding to avoid color strip
        Div(
            P(h.text, cls=TextPresets.md_weight_sm),
            cls="pl-4"
        ),
        footer=DivFullySpaced(
            DivHStacked(
                UkIcon(icon, height=16),
                P(h.title or h.source, cls=TextPresets.muted_sm)
            ),
            location_info
        ),
        cls=CardT.hover,
        style="position: relative;"
    )

# %% fasthlight.ipynb 30
@dataclass
class User:
    id: int
    email: str
    pwd_hash: str
    created: str

users_db = db.create(User, pk='id', transform=True)

# %% fasthlight.ipynb 32
def hash_pwd(pwd:str) -> str: return hashlib.sha256(pwd.encode()).hexdigest()

# %% fasthlight.ipynb 34
def verify_pwd(pwd:str, pwd_hash:str) -> bool: return hash_pwd(pwd) == pwd_hash

# %% fasthlight.ipynb 35
def get_current_user(session):
    user_id = session.get('user_id')
    if not user_id: return None
    try:
        return users_db[user_id]
    except NotFoundError:
        return None

# %% fasthlight.ipynb 37
# Initialize FastHTML app with MonsterUI theme
app, rt = fast_app(
    hdrs=Theme.blue.headers(),
    secret_key=os.getenv('SECRET_KEY')
)

# %% fasthlight.ipynb 38
# from starlette.middleware.cors import CORSMiddleware

# app, rt = fast_app(
#     hdrs=Theme.blue.headers(),
#     middleware=[
#         Middleware(
#             CORSMiddleware,
#             allow_origins=["*"],  # ⚠️ Only for development! 
#             allow_methods=["POST", "GET"],
#             allow_headers=["*"],
#         )
#     ]
# )

# %% fasthlight.ipynb 41
@rt('/')
def index(request, session):

    # check user authentication
    user = get_current_user(session)
    if not user: return RedirectResponse('/login', status_code=303)

    all_highlights = highlights_db(where="user_id=?", where_args=(user.id,))
    
    # Separate PDFs and web sources
    pdf_counts = Counter(h.source for h in all_highlights if h.source_type == 'pdf')
    web_counts = Counter(h.source for h in all_highlights if h.source_type == 'web')

    pdf_cards = [
        Card(
            DivLAligned(UkIcon('file-text', height=20),H3(f"{pdf_name}.pdf")),
            P(f'{count} highlights', cls=TextPresets.muted_sm),
            footer = Button("View Highlights",
                                     hx_get=f"/source/{pdf_name}?type=pdf",
                                     hx_target="#main-content",
                                     cls=ButtonT.primary),
            cls=CardT.hover
        )
        for pdf_name, count in pdf_counts.items()
    ]

    web_cards = [
        Card(
            DivLAligned(UkIcon('globe', height=20), H4(url[:50] + '...' if len(url) > 50 else url)),
            P(f'{count} highlights', cls=TextPresets.muted_sm),
            footer = Button("View",
                           hx_get=f"/source/{url}?type=web",
                           hx_target="#main-content",
                           cls=ButtonT.primary),
            cls=CardT.hover
        )
        for url, count in web_counts.items()
    ]

    # Upload form
    upload_form = Card(
        Form(
            UploadZone(
                DivCentered(
                    # Default state - show when no file selected
                    Div(
                        UkIcon('upload', height=48, width=48,cls=TextT.muted),
                        H4("Drop some PDF here or click to browse"),
                        P("Supports PDF files with highlights", cls=TextPresets.muted_sm),
                        id='upload-prompt',
                        cls='space-y-3'
                    ),
                    Div(
                        UkIcon('file-text', height=48, width=48, cls='text-primary'),
                        H4(id='file-name', cls='text-primary'),
                        P("Ready to upload", cls=TextPresets.muted_sm),
                        id='file-selected',
                        cls='space-y-3 hidden'
                    ),
                  # Uploading state - spinner
                    Div(
                        Loading(cls=(LoadingT.spinner, LoadingT.lg)),
                        H4("Analyzing PDF..."),
                        P("This may take a moment", cls=TextPresets.muted_sm),
                        id='upload-progress',
                        cls='space-y-3 htmx-indicator'
                    ),
                cls='space-y-3'
            ),
                Input(type="file", name="pdf_file", accept=".pdf", id="pdf_file",
                      onchange="document.getElementById('upload-prompt').classList.add('hidden'); document.getElementById('file-selected').classList.remove('hidden'); document.getElementById('file-name').textContent = this.files[0].name;"),
                cls='cursor-pointer border-2 border-dashed border-gray-300 hover:border-primary transition-colors rounded-lg p-8'
            ),
                Button(
                    DivLAligned(UkIcon('upload', height=16), "Upload & Analyze"), type="submit", 
                    cls=(ButtonT.primary, 'w-full', 'mt-4')),
            hx_post="/upload",
            hx_target="#upload-result",
            hx_indicator="#upload-progress",
            enctype="multipart/form-data",
            cls='space-y-4'
        ),
        # Result area
        Div(id='upload-result'),
        # Hidden trigger for reload
        header=H3("Upload New PDF"),
        cls='mb-8'
    )

    navbar = DivFullySpaced(
        H2("PDF Highlights Manager"),
        DivHStacked(
            P(f"Welcome, {user.email}", cls=TextPresets.muted_sm),
            Button("Logout", hx_get='/logout', cls=ButtonT.ghost)
        ),
        cls='mb-8'  # Add margin below navbar
    )
    
      # ✅ Build content once
    content = Container(
        Div(
            Loading(cls=(LoadingT.spinner, LoadingT.lg), htmx_indicator=True),
            id="upload-spinner",
            cls='hidden'
        ),
        Div(
            upload_form,
            
            # Bookmarklet card
            Card(
                DivFullySpaced(
                    Div(
                        H3("Web Highlights"),
                        P("Save highlights from any website", cls=TextPresets.muted_sm)
                    ),
                    A("Get Bookmarklet", href="/bookmarklet", cls=ButtonT.secondary)
                )
            ),
            
            Divider(),
            
            # PDFs section
            Div(
                H2("PDF Highlights"),
                Grid(*pdf_cards, cols=3) if pdf_cards else 
                    Card(P("No PDFs yet", cls=TextPresets.muted_sm), cls='text-center p-8'),
                cls='space-y-4 mb-8'
            ),
            
            # Web highlights section
            Div(
                H2("Web Highlights"),
                Grid(*web_cards, cols=3) if web_cards else 
                    Card(P("No web highlights yet", cls=TextPresets.muted_sm), cls='text-center p-8'),
                cls='space-y-4'
            ),
            
            id="main-content"
        ),
        cls='space-y-8 py-8'
    )
    if 'HX-Request' in request.headers:
        return content  # Just return the content div for HTMX
    else:
        return Titled("PDF Highlights Manager", Container(navbar, content, cls='py-8'))  # Full page for direct access

# %% fasthlight.ipynb 42
@rt('/source/{source:path}')
def view_source(source:str, type:str='pdf'):
    """Unified view for both PDF and web highlights"""
    highlights = highlights_db(where="source=? AND source_type=?", 
                               where_args=(source, type),
                               order_by='page' if type == 'pdf' else 'created')
    
    if not highlights:
        return Div(
            DivFullySpaced(
                H2(source),
                Button("← Back", hx_get="/", hx_target="#main-content", cls=ButtonT.ghost)
            ),
            Alert("No highlights found", cls=AlertT.info)
        )
    
    cards = [highlight_card(h) for h in highlights]
    
    return Div(
        DivFullySpaced(
            H2(source),
            Button("← Back", hx_get="/", hx_target="#main-content", cls=ButtonT.ghost)
        ),
        Div(*cards, cls='space-y-4')
    )

# %% fasthlight.ipynb 43
@rt('/upload', methods=['POST'])
async def upload(pdf_file: UploadFile, session):
    user = get_current_user(session)
    if not user: 
        return Div(
            Alert("Please login first to upload PDFs", cls=AlertT.error),
            RedirectResponse('/login', hx_trigger="load delay:2s")
        )
    # return 
    try:
        content = await pdf_file.read()
        new_highlights = extract_highlights(content)

        if not new_highlights: return Alert("No highlights found in this PDF", cls=AlertT.warning)
        save_highlights(pdf_file.filename, new_highlights, user.id)
    
        return Div(
            Alert(
                DivVStacked(
                    DivLAligned(
                        UkIcon('check-circle', cls='text-green-500'),
                        Strong(f"Success!")
                ),
                P(f"Extracted {len(new_highlights)} highlights from {pdf_file.filename}"),
                cls='space-y-2'
            ),
                cls=AlertT.success
            ),
            # Trigger a refresh to show the new PDF card
            Div(hx_get="/", hx_trigger="load delay:2s", hx_target="#main-content")
        )
        
    except Exception as e: return Alert(f"Error: {str(e)}", cls=AlertT.error)

# %% fasthlight.ipynb 45
@rt('/api/highlight', methods=['POST'])
async def save_web_highlight(text:str, url:str, color:str='#ffff00', title:str='', user_id:int=None):
    """API endpoint for saving web highlights from browser"""

    if not user_id: return {'status': 'error', 'message': 'Not authenticated'}
    
    highlights_db.insert(
        user_id=user_id,
        text=text,
        color=color,
        source=url,
        source_type='web',
        title=title or url,
        created=datetime.now().isoformat()
    )
    return {'status': 'success', 'message': 'Highlight saved!'}

# %% fasthlight.ipynb 47
@rt('/login')
def login_page():
    """Login page"""
    return Titled("Login",
                  Container(
                      Card(
                          Form(
                              LabelInput("Email", id="email", required=True),
                              LabelInput("Password", id="pwd", type='password', required=True),
                              Button("Login", cls=(ButtonT.primary, 'w-full'), type='submit'),
                              hx_post='/login',
                              hx_target="#login-result",
                              cls='space-y-4'
                          ),
                          Div(id="login-result"),
                          footer=DivCentered(
                               P("Don't have an account? ", A("Sign up", href='/signup', cls=AT.primary))
                          ),
                          header=H3("Welcome Back!")
                  ),
                      cls='max-w-md mx-auto mt-12'
                  )
                 )

# %% fasthlight.ipynb 48
@rt('/login', methods=['POST'])
def do_login(email:str, pwd: str, session):
    """Handle login"""
    try:
        user = users_db(where="email=?", where_args=(email,))[0]
        if verify_pwd(pwd, user.pwd_hash):
            session['user_id'] = user.id
            return Div(
                Alert("Login successful!", cls=AlertT.success),
                RedirectResponse()
            ) 
            
    except (IndexError, NotFoundError):
        pass
    return Alert("Invalid email or password", cls=AlertT.error)   

# %% fasthlight.ipynb 49
@rt('/signup')
def signup_page():
    """Signup page"""
    return Titled("Sign Up",
        Container(
            Card(
                Form(
                    LabelInput("Email", id='email', type='email', required=True),
                    LabelInput("Password", id='password', type='password', required=True),
                    LabelInput("Confirm Password", id='confirm_password', type='password', required=True),
                    Button("Sign Up", cls=(ButtonT.primary, 'w-full'), type='submit'),
                    hx_post='/signup',
                    hx_target='#signup-result',
                    cls='space-y-4'
                ),
                Div(id='signup-result'),
                footer=DivCentered(
                    P("Already have an account? ", A("Login", href='/login', cls=AT.primary))
                ),
                header=H3("Create Account")
            ),
            cls='max-w-md mx-auto mt-12'
        )
    )

# %% fasthlight.ipynb 50
@rt('/signup', methods=['POST'])
def do_signup(email: str, password: str, confirm_password: str, session):
    """Handle signup"""
    # Validation
    if password != confirm_password: return Alert("Passwords don't match", cls=AlertT.error)
    
    if len(password) < 8: return Alert("Password must be at least 8 characters", cls=AlertT.warning)
    
    # Check if user exists
    existing = users_db(where="email=?", where_args=(email,))
    if existing: return Alert("Email already registered", cls=AlertT.error)
    
    # Create user
    user = users_db.insert(
        email=email,
        pwd_hash=hash_pwd(password),
        created=datetime.now().isoformat()
    )
    
    # Auto-login
    session['user_id'] = user.id
    
    return Alert("Account created successfully!", cls=AlertT.success)

# %% fasthlight.ipynb 51
@rt('/logout')
def logout(session):
    """Logout"""
    session.clear()
    return RedirectResponse('/login', status_code=303)

# %% fasthlight.ipynb 54
@rt('/bookmarklet')
def bookmarklet_page():
    user = get_current_user(session)
    if not user: return RedirectResponse('/login', status_code=303)
    
    base_url = str(request.base_url).rstrip('/')
    # JavaScript bookmarklet code
    bookmarklet_js = f"""
    javascript:(function(){{
        const sel = window.getSelection().toString().trim();
        if(!sel) return alert('Please select some text first!');
        
        fetch('{base_url}/api/highlight', {{
            method: 'POST',
            headers: {{'Content-Type': 'application/x-www-form-urlencoded'}},
            body: new URLSearchParams({{
                text: sel,
                url: window.location.href,
                title: document.title,
                color: '#ffff00',
                user_id: '{user.id}'  // ← Add user_id
            }})
        }})
        .then(r => r.json())
        .then(d => alert(d.message))
        .catch(e => alert('❌ Error: ' + e));
    }})();
    """
    
    bookmarklet_link = A(
        "💡 Save Highlight",
        href=bookmarklet_js,
        cls=(ButtonT.primary, 'text-decoration-none')
    )
    
    return Titled(
        "Web Highlights Bookmarklet",
        Card(
            H3("How to use"),
            Ol(
                Li("Drag this button to your bookmarks bar:", cls='mb-2'),
                Li(bookmarklet_link, cls='mb-4'),
                Li("On any webpage, select text and click the bookmark"),
                Li("Your highlight will be saved automatically!"),
                cls='space-y-2'
            ),
            P("💡 Tip: Works on any website!", cls=TextPresets.muted_sm)
        )
    )

# %% fasthlight.ipynb 59
import os

if __name__ == "__main__":
    port = int(os.getenv("PORT", 8000))
    serve(port=port)
