# AUTOGENERATED! DO NOT EDIT! File to edit: fasthlight.ipynb.

# %% auto 0
__all__ = ['config', 'db', 'highlights_db', 'users_db', 'ph', 'beforeware', 'SECRET_KEY', 'app', 'rt', 'validate_environment',
           'AppConfig', 'HighlightData', 'rgb_to_hex', 'extract_highlights', 'Highlight', 'pdf_basename',
           'save_highlights', 'save_highlight', 'get_user_highlights', 'get_source_highlights', 'get_user_sources',
           'delete_highlight', 'get_user_by_email', 'create_user', 'UploadForm', 'NavBar', 'SourceCard', 'EmptyState',
           'BookmarkletCard', 'highlight_card', 'User', 'hash_pwd', 'verify_pwd', 'get_current_user', 'validate_email',
           'check_rate_limit', 'record_failed_attempt', 'clear_rate_limit', 'validate_web_highlight', 'auth_before',
           'index', 'view_source', 'upload', 'save_web_highlight', 'login_page', 'redirect_home', 'do_login',
           'signup_page', 'do_signup', 'logout', 'bookmarklet_page']

# %% fasthlight.ipynb 1
# fasthtml imports fastcore as well
from fasthtml.common import *
from fasthtml.jupyter import JupyUvi, HTMX
from monsterui.all import *
import os
import logging
from dotenv import load_dotenv

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# %% fasthlight.ipynb 2
import fitz  # PyMuPDF
from dataclasses import dataclass
from datetime import datetime
from collections import Counter
from typing import Union
from urllib.parse import urlparse

# %% fasthlight.ipynb 3
from argon2 import PasswordHasher
from argon2.exceptions import VerifyMismatchError 

# %% fasthlight.ipynb 4
load_dotenv() 

# %% fasthlight.ipynb 5
def validate_environment():
    "Ensure required environment variables are set"
    secret_key = os.getenv('SECRET_KEY')

    if not secret_key:
        raise RuntimeError(
            "❌ SECRET_KEY environment variable is required!\n"
            "Set it in your .env file or deployment environment.\n"
            "Generate one with: python -c 'import secrets; print(secrets.token_urlsafe(32))'"
        )

    if len(secret_key) < 32:
        raise RuntimeError(
            f"❌ SECRET_KEY is too short ({len(secret_key)} chars). "
            f"Must be at least 32 characters for security."
        )
    
    return secret_key

# %% fasthlight.ipynb 8
@dataclass
class AppConfig:
    """Application configuration"""
    # Highlight Validation
    max_highlight_length: int = 10_000
    max_url_length: int = 2_000
    max_title_length: int = 500
    default_highlight_color: str = '#ffff00'
    
    # File Upload
    max_pdf_size_mb: int = 10
    allowed_file_types: list = None
    
    # UI Timing
    upload_success_delay: int = 2
    login_success_delay: int = 1
    toast_duration: int = 5
    
    # Authentication
    min_password_length: int = 8
    session_max_age: int = 86400  # 24 hours (reduced from 1 year for security)

    # Database
    db_path: Path = None

    # Pagination
    highlights_per_page: int = 50
    sources_per_page: int = 20

    def __post_init__(self):
        if self.allowed_file_types is None: self.allowed_file_types = ['.pdf']

        # Use DB_PATH env var if set, otherwise use '/data' if it exists, else current dir
        if self.db_path is None:
            db_path_env = os.getenv('DB_PATH')
            if db_path_env:
                self.db_path = Path(db_path_env)
            elif Path('/data').exists():
                self.db_path = Path('/data')
            else:
                self.db_path = Path('.')

        self.db_path.mkdir(exist_ok=True)

    @property
    def max_pdf_size_bytes(self):
        """Convert MB to bytes for easier validation"""
        return self.max_pdf_size_mb * 1024 * 1024
    
    @property
    def db_file_path(self):
        """Full path to database file"""
        return self.db_path / 'highlights.db'

# Create global config instance
config = AppConfig()

# %% fasthlight.ipynb 10
@dataclass
class HighlightData:
    text: str
    page: int
    color: str  # We'll store as string for simplicity
    created: datetime  # ISO format datetime string

# %% fasthlight.ipynb 15
def rgb_to_hex(rgb_tuple):
    """Convert RGB tuple (0-1 range) to hex color string"""
    r, g, b = [int(c * 255) for c in rgb_tuple]
    return f"#{r:02x}{g:02x}{b:02x}"

# %% fasthlight.ipynb 17
def extract_highlights(pdf: Union[str, Path, bytes]):
    """Extract highlights from PDF file path or bytes content
    Returns tuple of (highlights_list, error_message)
    """
    QUAD_POINTS = 4  # PDF annotations use 4 corner points per quad

    highlights = L()
    doc = None
    
    try:
        
        doc = fitz.open(pdf) if isinstance(pdf, Path) else fitz.open(stream=pdf, filetype='pdf')

        # check if pdf is encrypted | protected by password
        if doc.is_encrypted: return highlights, "PDF is protected. Please remove the password first."
            
        for page_num in range(len(doc)):
            page = doc[page_num]
            annots = page.annots()
            if not annots: continue
            
            for annot in annots:
                # annotations (type 8), underline (9), strikeout (10), squiggly (11)
                if annot.type[0] not in [8, 9, 10, 11]: continue
    
                quads = annot.vertices
                highlighted_text = ""
                # Iterate through quads (each annotation has 4 corner points)
                for i in range(0, len(quads), QUAD_POINTS):
                    rect = fitz.Quad(quads[i:i+QUAD_POINTS]).rect
                    highlighted_text += page.get_text("text", clip=rect).strip()

                if not highlighted_text.strip(): continue
                
                hex_color = rgb_to_hex(annot.colors.get("stroke", (1.0, 1.0, 0.0)))
                
                highlights.append(HighlightData(
                    text=highlighted_text,
                    page=page_num + 1,
                    color=hex_color,
                    created=datetime.now()
                ))
        return True, highlights

    except Exception as e:
        error_msg = str(e)

        if "damaged" in error_msg.lower() or "corrupt" in error_msg.lower(): return False, "PDF file appears to be corrupted or damaged."
        elif "password" in error_msg.lower() or "encrypted" in error_msg.lower(): return highlights, "PDF is password protected."
        elif "format" in error_msg.lower(): return False, "Invalid PDF format."
        else: return False, f"Error reading PDF: {error_msg}"
        
    finally:
        if doc: doc.close()

# %% fasthlight.ipynb 22
# Create/open database
# data_dir = Path('/data') if Path('/data').exists() else Path('.')
# data_dir.mkdir(exist_ok=True)
db = database(config.db_file_path)

# Define your table structure - fastlite works great with dataclasses
@dataclass
class Highlight:
    id: int
    user_id: int
    text: str
    color: str  # We'll store as string for simplicity
    source: str # PDF filename or URL
    source_type: str # 'pdf' or 'web'
    title: str  # Page title for web highlights
    created: str  # ISO format datetime string
    page: int = None

# Create the table (transform=True allows schema updates)
highlights_db = db.create(Highlight, pk='id', transform=True)

db.execute('CREATE INDEX IF NOT EXISTS idx_user_source ON highlight(user_id, source)')
db.execute('CREATE INDEX IF NOT EXISTS idx_user_type ON highlight(user_id, source_type)')
db.execute('CREATE INDEX IF NOT EXISTS idx_user_source_type ON highlight(user_id, source, source_type)')

# %% fasthlight.ipynb 25
def pdf_basename(filename):
    """Get filename without extension and sanitize for security"""
    import re
    # Get just the filename (removes any path components)
    base = Path(filename).name
    # Remove extension
    stem = Path(base).stem
    # Remove any dangerous characters, keep only alphanumeric, spaces, hyphens, underscores
    sanitized = re.sub(r'[^\w\s\-]', '', stem)
    # Limit length to prevent issues
    return sanitized[:255] if sanitized else 'untitled'

# %% fasthlight.ipynb 27
def save_highlights(pdf_path, highlights, user_id):
    "Save extracted highlights to database using a transaction (all or nothing)"
    pdf_name = pdf_basename(pdf_path)

    try:
        conn = highlights_db.db.conn

        with conn:
            for h in highlights:
                highlights_db.insert(
                    user_id=user_id,
                    text=h.text,
                    page=h.page,
                    color=h.color,  # Convert tuple to string
                    source=pdf_name,
                    source_type='pdf',
                    title=f"{pdf_name}.pdf",
                    created=h.created.isoformat()
                )
        return True, None
    except Exception as e: return False, f"Failed to save highlights: {str(e)}"

# %% fasthlight.ipynb 33
def save_highlight(user_id, text, source, 
                   source_type, color='#ffff00', title='', page=None):
    """Save a single highlight to database
    
    Returns tuple of (success, error_message)
    """
    try:
        highlights_db.insert(
            user_id=user_id,
            text=text,
            page=page,
            color=color,
            source=source,
            source_type=source_type,
            title=title,
            created=datetime.now().isoformat()
        )
        return True, None
    except Exception as e:
        return False, str(e)

# %% fasthlight.ipynb 34
def get_user_highlights(user_id, source_type=None):
    """Get all highlights for a user, optionally filtered by type
    
    Args:
        user_id: User ID to filter by
        source_type: Optional 'pdf' or 'web' to filter by type
    
    Returns:
        List of Highlight objects
    """
    if source_type:
        return highlights_db(where="user_id=? AND source_type=?", where_args=(user_id, source_type))
    else:
        return highlights_db(where="user_id=?", where_args=(user_id,))                      

# %% fasthlight.ipynb 35
def get_source_highlights(user_id, source, source_type='pdf'):
    """Get all highlights for a specific source (PDF or web URL)
    
    Args:
        user_id: User ID to filter by
        source: PDF filename or web URL
        source_type: 'pdf' or 'web'
    
    Returns:
        List of Highlight objects, ordered by page (PDF) or created date (web)
    """
    order_by = 'page' if source_type == 'pdf' else 'created'
    return highlights_db(where="user_id=? AND source=? AND source_type=?", where_args=(user_id, source, source_type), order_by=order_by)

# %% fasthlight.ipynb 36
def get_user_sources(user_id, source_type='pdf'):
    """Get unique sources for a user with highlight counts
    
    Args:
        user_id: User ID to filter by
        source_type: 'pdf' or 'web'
    
    Returns:
        Counter object with {source: count} pairs
    """
    highlights = get_user_highlights(user_id, source_type)
    return Counter(h.source for h in highlights)

# %% fasthlight.ipynb 37
def delete_highlight(highlight_id, user_id):
    """Delete a highlight (with user ownership check)
    
    Args:
        highlight_id: ID of highlight to delete
        user_id: User ID (for ownership verification)
    
    Returns:
        tuple of (success, error_message)
    """
    try:
        highlight = highlights_db[highlight_id]
        if highlight.user_id != user_id: return False, "Not authorized to delete this highlight"
        highlights_db.delete(highlight_id)
        return True, None

    except NotFoundError: return False, "Highlight not found"
    except Exception as e: return False, str(e)

# %% fasthlight.ipynb 38
def get_user_by_email(email):
    try:
        return users_db(where="email=?", where_args=(email,))[0]
    except (IndexError, NotFoundError):
        return None

# %% fasthlight.ipynb 39
def create_user(email, password):
    try:
        if get_user_by_email(email): return False, "Email already registered"
        user = users_db.insert(
            email=email,
            pwd_hash=hash_pwd(password),
            created=datetime.now().isoformat()
        )
        return True, user

    except Exception as e: return False, str(e)

# %% fasthlight.ipynb 42
def UploadForm():
    return Card(
        Form(
            UploadZone(
                DivCentered(
                    # Default state - show when no file selected
                    DivCentered(
                        UkIcon('upload', height=48, width=48,cls=TextT.muted),
                        H4("Drop some PDF here or click to browse"),
                        P("Supports PDF files with highlights", cls=TextPresets.muted_sm),
                        id='upload-prompt',
                        cls='space-y-3'
                    ),
                    # File selected state
                    DivCentered(
                        UkIcon('file-text', height=48, width=48, cls='text-primary'),
                        H4(id='file-name', cls='text-primary'),
                        P("Ready to upload", cls=TextPresets.muted_sm),
                        id='file-selected',
                        cls='space-y-3 hidden'
                    ),
                  # Uploading state - spinner
                    Div(
                        Loading(cls=(LoadingT.spinner, LoadingT.lg)),
                        H4("Analyzing PDF..."),
                        P("This may take a moment", cls=TextPresets.muted_sm),
                        id='upload-progress',
                        cls='space-y-3 htmx-indicator'
                    ),
                cls='space-y-3'
            ),
                Input(type="file", 
                      name="pdf_file", 
                      accept=".pdf", 
                      id="pdf_file",
                      onchange="document.getElementById('upload-prompt').classList.add('hidden'); document.getElementById('file-selected').classList.remove('hidden'); document.getElementById('file-name').textContent = this.files[0].name;"),
                cls='cursor-pointer border-2 border-dashed border-gray-300 hover:border-primary transition-colors rounded-lg p-8'
            ),
                Button(
                    DivLAligned(UkIcon('upload', height=16), "Upload & Analyze"), 
                    type="submit", 
                    cls=(ButtonT.primary, 'w-full', 'mt-4')),
            hx_post="/upload",
            hx_target="#upload-result",
            hx_indicator="#upload-progress",
            enctype="multipart/form-data",
            cls='space-y-4'
        ),
        Div(id='upload-result'),
        header=H3("Upload New PDF"),
        cls='mb-8'
    )

# %% fasthlight.ipynb 44
def NavBar(user):
    "Top navigation bar with user info, theme toggle, and logout"
    return DivFullySpaced(
        DivLAligned(
            UkIcon('bookmark', height=24),
            H2("Highlights")
        ),
        DivHStacked(
            Button(
                UkIcon('sun', height=16),
                onclick="document.documentElement.classList.toggle('dark')",
                cls=ButtonT.ghost,
                title="Toggle theme"
            ),
            Div(cls='w-px h-6 bg-gray-300 dark:bg-gray-600'),  # Separator
            P(user.email, cls=TextPresets.muted_sm),
            A("Logout", href="/logout", cls=ButtonT.ghost)
        ),
        cls='mb-8 pb-4 border-b'
    )

# %% fasthlight.ipynb 46
def SourceCard(source, count, source_type='pdf'):
    "Card showing a single PDF or web source with highlight count"
    icon = 'file-text' if source_type=="pdf" else "globe"
    display_name = (source[:50] + '...' if len(source) > 50 else source)

    return Card(
        DivFullySpaced(
            DivLAligned(UkIcon(icon, height=20), H3(display_name) if source_type == 'pdf' else H4(display_name)),
            Span(str(count), cls='px-2 py-1 text-xs font-semibold rounded-full bg-primary text-white')  # Badge for count
        ),
        P(f'{count} highlights', cls=TextPresets.muted_sm),
        footer=Button(
            "View Highlights" if source_type == 'pdf' else "View",
            hx_get=f"/source/{source}?type={source_type}",
            hx_target="#main-content",
            cls=ButtonT.primary
        ),
        cls=CardT.hover
    )

# %% fasthlight.ipynb 48
def EmptyState(type='pdf'):
    "Empty state message when no sources exist"
    icon = 'file-text' if type == 'pdf' else 'globe'
    message = "No PDFs yet" if type == 'pdf' else "No web highlights yet"
    cta = "Upload a PDF above to get started" if type == 'pdf' else "Get the bookmarklet to save web highlights"

    return Card(
        DivCentered(
            UkIcon(icon, height=48, width=48, cls='text-muted'),
            H3(message, cls='mt-4'),
            P(cta, cls=TextPresets.muted_sm)
        ),
        cls='p-12'
    )

# %% fasthlight.ipynb 49
def BookmarkletCard():
    "Card with link to bookmarklet page"
    return Card(
        DivFullySpaced(
            Div(
                H3("Web Highlights"),
                P("Save highlights from any website", cls=TextPresets.muted_sm)
            ),
            A("Get Bookmarklet", href="/bookmarklet", cls=ButtonT.secondary)
        )
    )

# %% fasthlight.ipynb 51
def _get_source_icon(source_type):
    """Get icon name for source type"""
    return 'file-text' if source_type == 'pdf' else 'globe'

# %% fasthlight.ipynb 52
def _get_location_info(h):
    """Generate location info component based on highlight type"""
    if h.source_type == 'pdf':
        return DivHStacked(
            UkIcon('book-open', height=16),
            P(f"Page {h.page}", cls=TextPresets.muted_sm)
        )
    else:
        # Extract domain from URL for cleaner display
        domain = urlparse(h.source).netloc or h.source
        return DivHStacked(
            UkIcon('link', height=16),
            P(domain, cls=TextPresets.muted_sm)
        )


# %% fasthlight.ipynb 53
def _get_color_strip(color):
    """Create colored indicator strip for highlight"""
    return Div(
        cls="absolute left-0 top-0 bottom-0 w-1",
        style=f"background-color: {color};"
    )

# %% fasthlight.ipynb 54
def highlight_card(h):
    "Render a highlight card for both PDF and web highlights"

    icon = _get_source_icon(h.source_type)
    location_info = _get_location_info(h)
    color_strip = _get_color_strip(h.color)

    return Card(
        # Color indicator strip - using inline style instead of Tailwind classes
        color_strip,
        # Main content with padding to avoid color strip
        Div(
            P(h.text, cls=TextPresets.md_weight_sm),
            cls="pl-4"
        ),
        footer=DivFullySpaced(
            DivHStacked(
                UkIcon(icon, height=16),
                P(h.title or h.source, cls=TextPresets.muted_sm)
            ),
            location_info
        ),
        cls='relative hover:shadow-lg transition-shadow ' + CardT.hover,
        style="position: relative;"
    )

# %% fasthlight.ipynb 56
@dataclass
class User:
    id: int
    email: str
    pwd_hash: str
    created: str

users_db = db.create(User, pk='id', transform=True)
db.execute('CREATE INDEX IF NOT EXISTS idx_user_email ON user(email)')

# %% fasthlight.ipynb 59
ph = PasswordHasher()

# %% fasthlight.ipynb 60
def hash_pwd(pwd:str) -> str:
    "Hash a password using Argon2"
    return ph.hash(pwd)

# %% fasthlight.ipynb 62
def verify_pwd(pwd:str, pwd_hash:str) -> bool:
    "Verify a password against its hash"
    try:
        ph.verify(pwd_hash, pwd)
        return True
    except VerifyMismatchError:
        return False

# %% fasthlight.ipynb 63
def get_current_user(session):
    user_id = session.get('user_id')
    if not user_id: return None
    try:
        return users_db[user_id]
    except NotFoundError:
        return None

# %% fasthlight.ipynb 64
def validate_email(email: str) -> bool:
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return re.match(pattern, email) is not None

# %% fasthlight.ipynb 66
def check_rate_limit(session, action='login', max_attempts=5, window_seconds=300) -> tuple:
    """Check if action is rate limited
    
    Args:
        session: Starlette session
        action: Action name ('login' or 'signup')
        max_attempts: Max attempts allowed
        window_seconds: Time window in seconds (default 5 minutes)
    
    Returns:
        tuple of (is_allowed, attempts_remaining, time_until_reset)
    """
    import time
    key_attempts = f'{action}_attempts'
    key_timestamp = f'{action}_first_attempt'

    current_time = time.time()
    attempts = session.get(key_attempts, 0)
    first_attempt = session.get(key_timestamp, current_time)

    if current_time - first_attempt > window_seconds:
        session[key_attempts] = 0
        session[key_timestamp] = current_time
        return True, max_attempts, 0

    if attempts >= max_attempts:
        time_remaining = int(window_seconds - (current_time - first_attempt))
        return False, 0, time_remaining

    return True, max_attempts-attempts, 0

# %% fasthlight.ipynb 67
def record_failed_attempt(session, action='login'):
    "Record a failed attempt"
    import time
    key_attempts = f'{action}_attempts'
    key_timestamp = f'{action}_first_attempt'

    attempts = session.get(key_attempts,0)
    if attempts == 0: session[key_timestamp] = time.time()
    session[key_attempts] = attempts + 1

# %% fasthlight.ipynb 68
def clear_rate_limit(session, action='login'):
    "Clear rate limit on successful action"
    session.pop(f'{action}_attempts', None)
    session.pop(f'{action}_first_attempt', None)

# %% fasthlight.ipynb 71
def validate_web_highlight(text, url, color, title) -> tuple:
    """Validate web highlight data
    Returns tuple of (is_valid, error_message, cleaned_data)
    """
    import re
    # validate text
    text = text.strip()
    if not text: return False, 'Highlight text cannot be empty', None
    if len(text) > config.max_highlight_length: return False, 'Highlight text too long (max 10,000 characters)', None

    # Validate color
    if not re.match(r'^#[0-9A-Fa-f]{6}$', color): color = config.default_highlight_color # Default to yellow

    # Validate URL
    url = url.strip()
    if not url: return False, 'URL cannot be empty', None
    if not url.startswith(('http://', 'https://')): return False, 'Invalid URL format', None
    if len(url) > 2000: return False, 'URL too long', None

    # Validate | fix title
    title = title.strip()
    if len(title) > config.max_title_length: title = title[:config.max_title_length]
    if not title:
        try: title = urlparse(url).netloc or url
        except: title = url

    return True, None, {
        'text': text,
        'url': url,
        'color': color,
        'title': title
    }

# %% fasthlight.ipynb 73
def auth_before(req, sess):
    "Beforeware to check authentification and inject user into request scope"
    # get current user from session
    user = get_current_user(sess)
    req.scope['auth'] = user
    if not user:
        logger.info("Unauthenticated user - redirecting to /login")
        return RedirectResponse('/login', status_code=303)
    
beforeware = Beforeware(
    auth_before,
    skip = [
        r'/favicon\.ico',      # Skip favicon
        r'/static/.*',         # Skip static files
        r'.*\.css',            # Skip CSS
        r'.*\.js',             # Skip JS
        '/login',              # Skip login page
        '/signup',             # Skip signup page
        '/do_login',           # Skip login handler (not needed, but explicit)
        '/do_signup',          # Skip signup handler (not needed, but explicit)
    ]
)

# %% fasthlight.ipynb 74
SECRET_KEY = validate_environment()

app, rt = fast_app(
    hdrs=Theme.blue.headers(mode='auto') + [Style("""
        /* Dark mode adjustments for highlight color strips */
        .highlight-strip {
            transition: opacity 0.3s ease;
        }
        .dark .highlight-strip {
            opacity: 0.8;
        }
        /* Smooth transitions for theme changes */
        html {
            transition: background-color 0.3s ease, color 0.3s ease;
        }
    """)],  # Custom CSS for theme support
    secret_key=SECRET_KEY,
    before=beforeware
)

# %% fasthlight.ipynb 77
@rt('/')
def index(request):
    """Main dashboard showing all highlight sources"""
    user = request.scope['auth']
    pdf_counts = get_user_sources(user.id, 'pdf')
    web_counts = get_user_sources(user.id, 'web')

    pdf_cards = [SourceCard(source, count, 'pdf') for source, count in pdf_counts.items()]
    web_cards = [SourceCard(source, count, 'web') for source, count in web_counts.items()]
    
    content = Container(
        Div(
            UploadForm(),
            BookmarkletCard(),
            Divider(),
            
            # PDFs section
            Div(
                H2("PDF Highlights"),
                Grid(*pdf_cards, cols=1, cols_md=2, cols_lg=3) if pdf_cards else EmptyState('pdf'),
                cls='space-y-4 mb-8'
            ),

            # Web highlights section
            Div(
                H2("Web Highlights"),
                Grid(*web_cards, cols=1, cols_md=2, cols_lg=3) if web_cards else EmptyState('web'),
                cls='space-y-4'
            ),
            
            id="main-content"
        ),
        cls='space-y-8 py-8'
    )
    if 'HX-Request' in request.headers:
        return content  # Just return the content div for HTMX
    else:
        return Titled("PDF Highlights Manager", Container(NavBar(user), content, cls='py-8'))  # Full page for direct access

# %% fasthlight.ipynb 79
@rt('/source/{source:path}')
def view_source(request, source:str, type:str='pdf'):
    """Unified view for both PDF and web highlights"""
    user = request.scope['auth']
    highlights = get_source_highlights(user.id, source, type)
    
    if not highlights:
        return Div(
            DivFullySpaced(
                H2(source),
                Button("← Back", hx_get="/", hx_target="#main-content", cls=ButtonT.ghost)
            ),
            Alert("No highlights found", cls=AlertT.info)
        )
    
    cards = [highlight_card(h) for h in highlights]
    
    return Div(
        DivFullySpaced(
            H2(source),
            Button("← Back", hx_get="/", hx_target="#main-content", cls=ButtonT.ghost)
        ),
        Div(*cards, cls='space-y-4')
    )

# %% fasthlight.ipynb 81
@rt('/upload', methods=['POST'])
async def upload(request, pdf_file: UploadFile):

    user = request.scope['auth']
    try:
        # Validate MIME type
        if pdf_file.content_type != 'application/pdf':
            return Toast("Only PDF files are allowed", alert_cls=AlertT.error, cls=(ToastVT.top, ToastHT.end))

        content = await pdf_file.read()

        if len(content) > config.max_pdf_size_bytes: return Toast(f"PDF too large. Maximum size is {config.max_pdf_size_mb}MB", 
                                                                  alert_cls=AlertT.error,
                                                                  cls=(ToastVT.top, ToastHT.end))
        
        success, result = extract_highlights(content)

        if not success: return Toast(f"Could not extract highlights: {result}", alert_cls=AlertT.error, cls=(ToastVT.top, ToastHT.end))
        if not result: return Toast("No highlights found in this PDF", alert_cls=AlertT.warning, cls=(ToastVT.top, ToastHT.end))
        new_highlights = result
        
        success, error = save_highlights(pdf_file.filename, new_highlights, user.id)
        if not success: return Toast(f"Failed to save highlights: {error}", alert_cls=AlertT.error, cls=(ToastVT.top, ToastHT.end))
        
        return Div(
            Toast(
                f"✅ Extracted {len(new_highlights)} highlights from {pdf_file.filename}",
                alert_cls=AlertT.success,
                cls=(ToastVT.top, ToastHT.end),
                dur=3  # 3 seconds
            ),
            # Trigger a refresh to show the new PDF card
            Div(hx_get="/", hx_trigger=f"load delay:{config.upload_success_delay}s", hx_target="#main-content")
        )
        
    except Exception as e: return Toast(f"Unexpected error: {str(e)}", alert_cls=AlertT.error, cls=(ToastVT.top, ToastHT.end))

# %% fasthlight.ipynb 83
@rt('/api/highlight', methods=['POST'])
async def save_web_highlight(text:str, url:str, color:str='#ffff00', 
                             title:str='', session=None):
    "API endpoint for saving web highlights from browser"

    user = get_current_user(session)
    if not user: return {'status': 'error', 'message': 'Not authenticated. Please log in first.'}

    success, result = validate_web_highlight(text, url, color, title)
    if not success: return {'status': 'error', 'message': result}

    data = result
    success, error = save_highlight(
        user_id=user.id,
        text=data['text'],
        source=data['url'],
        source_type='web',
        color=data['color'],
        title=data['title']
    )

    if not success: return {'status': 'error', 'message': f'Failed to save: {error}'}
    return {'status': 'success', 'message':'Highlight saved!'}

# %% fasthlight.ipynb 86
@rt('/login',methods=['GET'])
def login_page():
    """Login page"""
    return Titled("Login",
        Container(
            # Branding card
            Card(
                DivCentered(
                    UkIcon('bookmark', height=48, cls='text-primary'),
                    H2("Highlights"),
                    P("Welcome back! Sign in to view your highlights.", cls=TextPresets.muted_sm)
                ),
                cls='mb-6'
            ),
            # Login form card
            Card(
                Form(
                    LabelInput("Email", id="email", required=True),
                    LabelInput("Password", id="pwd", type='password', required=True),
                    Button("Login", cls=(ButtonT.primary, 'w-full'), type='submit'),
                    hx_post='/login',
                    hx_target="#login-result",
                    cls='space-y-4'
                ),
                Div(id="login-result"),
                footer=DivCentered(
                    P("Don't have an account? ", A("Sign up", href='/signup', cls=AT.primary))
                ),
                header=H3("Sign In")
            ),
            cls='max-w-md mx-auto mt-12'
        )
    )

# %% fasthlight.ipynb 87
@rt('/redirect-home')
def redirect_home():
    "Helper route for delayed redirects"
    return HtmxResponseHeaders(redirect='/')

# %% fasthlight.ipynb 88
@rt('/login', methods=['POST'])
def do_login(email: str, pwd: str, session):
    """Handle login"""

    # check rate limit
    is_allowed, attempts_left, time_remaining = check_rate_limit(session)

    if not is_allowed:
        mins = time_remaining // 60
        secs = time_remaining % 60
        return Toast(
            f"Too many failed login attempts. Please try again in {mins}m {secs}s",
            alert_cls=AlertT.error, cls=(ToastVT.top, ToastHT.end)
        )

    user = get_user_by_email(email)
    
    if user and verify_pwd(pwd, user.pwd_hash):
        clear_rate_limit(session)
        session['user_id'] = user.id
        # ✅ Use HX-Redirect header for full page redirect
        return Div(
            Toast("Login successful!", alert_cls=AlertT.success, cls=(ToastVT.top, ToastHT.end)),
            Div(hx_get="/redirect-home",hx_trigger=f'load delay:{config.login_success_delay}s')
        )

    record_failed_attempt(session)
    _, attempts_left, _ = check_rate_limit(session)

    if attempts_left > 0:
        return Toast(
            f"Invalid email or password. {attempts_left} attempts remaining.",
            alert_cls=AlertT.error, cls=(ToastVT.top, ToastHT.end)
        )
    
    else:
        return Toast(
            "Too many failed attempts. Please try again in 5 minutes.",
            alert_cls=AlertT.error, cls=(ToastVT.top, ToastHT.end)
        )

# %% fasthlight.ipynb 90
@rt('/signup', methods=['GET'])
def signup_page():
    """Signup page"""
    return Titled("Sign Up",
        Container(
            # Branding card
            Card(
                DivCentered(
                    UkIcon('bookmark', height=48, cls='text-primary'),
                    H2("Highlights"),
                    P("Create an account to start saving your highlights.", cls=TextPresets.muted_sm)
                ),
                cls='mb-6'
            ),
            # Signup form card
            Card(
                Form(
                    LabelInput("Email", id='email', type='email', required=True),
                    LabelInput("Password", id='password', type='password', required=True),
                    LabelInput("Confirm Password", id='confirm_password', type='password', required=True),
                    Button("Sign Up", cls=(ButtonT.primary, 'w-full'), type='submit'),
                    hx_post='/signup',
                    hx_target='#signup-result',
                    cls='space-y-4'
                ),
                Div(id='signup-result'),
                footer=DivCentered(
                    P("Already have an account? ", A("Login", href='/login', cls=AT.primary))
                ),
                header=H3("Create Account")
            ),
            cls='max-w-md mx-auto mt-12'
        )
    )

# %% fasthlight.ipynb 92
@rt('/signup', methods=['POST'])
def do_signup(email: str, password: str, confirm_password: str, session):
    """Handle signup"""
    logger.info(f"Signup attempt for email: {email[:3]}***")  # Log first 3 chars for privacy

    if not validate_email(email): return Toast("Please enter a valid email address", alert_cls=AlertT.error, cls=(ToastVT.top, ToastHT.end))

    if password != confirm_password:
        logger.warning("Signup failed: Passwords don't match")
        return Toast("Passwords don't match", alert_cls=AlertT.error)

    if len(password) < config.min_password_length:
        logger.warning("Signup failed: Password too short")
        return Toast(f"Password must be at least {config.min_password_length} characters", alert_cls=AlertT.warning, cls=(ToastVT.top, ToastHT.end))

    success, result = create_user(email, password)
    if not success:
        logger.error(f"Create user failed: {result}")
        return Toast(result, alert_cls=AlertT.error, cls=(ToastVT.top, ToastHT.end))

    user = result
    session['user_id'] = user.id
    logger.info(f"User created successfully: {user.id}")
    
    return Div(
        Toast("Account created successfully!", alert_cls=AlertT.success, cls=(ToastVT.top, ToastHT.end)),
        Div(hx_get="/redirect-home", hx_trigger=f"load delay:{config.login_success_delay}s")
    )


# %% fasthlight.ipynb 94
@rt('/logout')
def logout(session):
    """Logout"""
    session.clear()
    return RedirectResponse('/login', status_code=303)

# %% fasthlight.ipynb 98
@rt('/bookmarklet')
def bookmarklet_page(request):
    # user = request.scope['auth']
    base_url = str(request.base_url).rstrip('/')
    # JavaScript bookmarklet code
    bookmarklet_js = f"""
    javascript:(function(){{
        const sel = window.getSelection().toString().trim();
        if(!sel) return alert('Please select some text first!');
        
        fetch('{base_url}/api/highlight', {{
            method: 'POST',
            credentials: 'include',
            headers: {{'Content-Type': 'application/x-www-form-urlencoded'}},
            body: new URLSearchParams({{
                text: sel,
                url: window.location.href,
                title: document.title,
                color: '#ffff00'
            }})
        }})
        .then(r => r.json())
        .then(d => alert(d.message))
        .catch(e => alert('❌ Error: ' + e));
    }})();
    """
    
    bookmarklet_link = A(
        "💡 Save Highlight",
        href=bookmarklet_js,
        cls=(ButtonT.primary, 'text-decoration-none')
    )
    
    return Titled(
        "Web Highlights Bookmarklet",
        Card(
            H3("How to use"),
            Ol(
                Li("Drag this button to your bookmarks bar:", cls='mb-2'),
                Li(bookmarklet_link, cls='mb-4'),
                Li("On any webpage, select text and click the bookmark"),
                Li("Your highlight will be saved automatically!"),
                cls='space-y-2'
            ),
            P("💡 Tip: Works on any website!", cls=TextPresets.muted_sm)
        )
    )

# %% fasthlight.ipynb 104
import os

if __name__ == "__main__":
    port = int(os.getenv("PORT", 8000))
    serve(port=port)
